
package net.tedata.webservices.fe_getactiondestinationforcustomer;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebFault(name = "ESBGeneralException", targetNamespace = "http://webservices.tedata.net/FE_GetActionDestinationForCustomer")
public class ESBGeneralExceptionMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private ESBGeneralException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public ESBGeneralExceptionMessage(String message, ESBGeneralException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ESBGeneralExceptionMessage(String message, ESBGeneralException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: net.tedata.webservices.fe_getactiondestinationforcustomer.ESBGeneralException
     */
    public ESBGeneralException getFaultInfo() {
        return faultInfo;
    }

}
