
package net.tedata.webservices.fe_getactiondestinationforcustomer;

import javax.xml.ws.WebFault;
import net.tedata.webservices.v3.tedatacommontypes.FaultResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "FE_getActionDestinationForCustomerFault", targetNamespace = "http://webservices.tedata.net/FE_GetActionDestinationForCustomer")
public class FEGetActionDestinationForCustomerFaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultResponseType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FEGetActionDestinationForCustomerFaultMsg(String message, FaultResponseType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public FEGetActionDestinationForCustomerFaultMsg(String message, FaultResponseType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: net.tedata.webservices.v3.tedatacommontypes.FaultResponseType
     */
    public FaultResponseType getFaultInfo() {
        return faultInfo;
    }

}
