
package net.tedata.webservices.fe_getactiondestinationforcustomer;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FE_GetActionDestinationForCustomerPortType", targetNamespace = "http://webservices.tedata.net/FE_GetActionDestinationForCustomer")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    net.tedata.webservices.fe_getactiondestinationforcustomer.ObjectFactory.class,
    net.tedata.webservices.v3.tedatacommontypes.ObjectFactory.class
})
public interface FEGetActionDestinationForCustomerPortType {


    /**
     * 
     * @param feGetActionDestinationForCustomerRequest
     * @return
     *     returns net.tedata.webservices.fe_getactiondestinationforcustomer.FEGetActionDestinationForCustomerResponseType
     * @throws FEGetActionDestinationForCustomerFaultMsg
     * @throws ESBGeneralExceptionMessage
     */
    @WebMethod(operationName = "FE_getActionDestinationForCustomer", action = "http://FE_GetActionDestinationForCustomer/FE_getActionDestinationForCustomer")
    @WebResult(name = "FE_getActionDestinationForCustomerResponse", targetNamespace = "http://webservices.tedata.net/FE_GetActionDestinationForCustomer", partName = "FE_getActionDestinationForCustomerResponse")
    public FEGetActionDestinationForCustomerResponseType feGetActionDestinationForCustomer(
        @WebParam(name = "FE_getActionDestinationForCustomerRequest", targetNamespace = "http://webservices.tedata.net/FE_GetActionDestinationForCustomer", partName = "FE_getActionDestinationForCustomerRequest")
        FEGetActionDestinationForCustomerRequestType feGetActionDestinationForCustomerRequest)
        throws ESBGeneralExceptionMessage, FEGetActionDestinationForCustomerFaultMsg
    ;

}
